services:
  - type: web
    name: eventrize
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      mkdir -p database
      touch database/database.sqlite
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT